set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR x86) # force use 32bit

#set(WINDOWS_TOOLCHAIN_NAME    x86_64-w64-mingw32-)
#set(CMAKE_C_COMPILER    ${WINDOWS_TOOLCHAIN_NAME}gcc-posix)
#set(CMAKE_CXX_COMPILER  ${WINDOWS_TOOLCHAIN_NAME}g++-posix)
#
#SET(CMAKE_RC_COMPILER   ${WINDOWS_TOOLCHAIN_NAME}windres)
#set(CMAKE_AR            ${WINDOWS_TOOLCHAIN_NAME}ar CACHE FILEPATH "Archiver")
#set(CMAKE_RANLIB        ${WINDOWS_TOOLCHAIN_NAME}ranlib CACHE FILEPATH "Ranlib")
#set(CMAKE_ASM_COMPILER  ${WINDOWS_TOOLCHAIN_NAME}as)
#set(CMAKE_LINKER        ${WINDOWS_TOOLCHAIN_NAME}ld)
#set(CMAKE_NM            ${WINDOWS_TOOLCHAIN_NAME}nm)
#set(CMAKE_OBJCOPY       ${WINDOWS_TOOLCHAIN_NAME}objcopy)
#set(CMAKE_OBJDUMP       ${WINDOWS_TOOLCHAIN_NAME}objdump)
#set(CMAKE_STRIP         ${WINDOWS_TOOLCHAIN_NAME}strip)

# project. static linking c++ library
include(${CMAKE_CURRENT_LIST_DIR}/base.cmake)
